provider "aws" {
  region = "us-east-2"
}
resource "aws_instance" "practice" {
  ami           = data.aws_ami.CentOs.image_id
  instance_type = "t2.micro"
  key_name = "PractiseKeypair"
  security_groups = [data.aws_security_group.sg.name]
  tags = {
    Name = "practice"
  }

  provisioner "remote-exec" {
    connection {
      type = "ssh"
      user = "centos"
      host = self.private_ip
      private_key = file("/home/centos/.ssh/id_rsa")
    }
    inline = [
      "sudo yum install epel-release -y"
      "sudo yum install ansible -y"

    ]
  }
}
data "aws_ami" "CentOs" {
  most_recent = true
  filter {
    name   = "name"
    values = ["CentOS Linux 7 x86_64 HVM EBS ENA 2002_01-b7ee8a69-ee97-4a49-9e68-afaee216db2e-ami-0042af67f8e4dcc20.4"]
  }
  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
  owners = ["679593333241"] # Canonical
}
data "aws_security_group" "sg" {
  filter {
    name = "description"
    values = ["This security group was generated by AWS Marketplace and is based on recommended settings for CentOS 7 (x86_64) - with Updates HVM version 2002_01 provided by Centos.org"]
  }
}
